/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See LICENSE in the project root for license information.
 *--------------------------------------------------------------------------------------------*/
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace Spp.Data.Entities
{
    public partial class PlayerMetric : EntityBase
    {
        public string Name { get; set; }
        public string Type { get; set; }
        public string ShortName { get; set; }
        public string FullName { get; set; }
        public string Tooltip { get; set; }
        public Nullable<int> MetricSetId { get; set; }
    }
}
