/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See LICENSE in the project root for license information.
 *--------------------------------------------------------------------------------------------*/
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace Spp.Data.Entities
{

    public partial class PracticeDrillData : EntityBase
    {
        [ForeignKey("Practice")]
        public int PracticeId { get; set; }

        [ForeignKey("PracticeDrill")]
        public Nullable<int> PracticeDrillId { get; set; }

        public bool isModified { get; set; }
        public Nullable<decimal> Duration { get; set; }
        public string DrillArea { get; set; }
        public Nullable<int> DrillLength { get; set; }
        public Nullable<int> DrillWidth { get; set; }
        public Nullable<int> NumberOfPlayers { get; set; }
        public Nullable<int> CalculatedTrainingLoad { get; set; }
        [ForeignKey("Note")]
        public Nullable<int> NoteId { get; set; }

        //Navigation properties
        public Practice Practice { get; set; }
        public PracticeDrill PracticeDrill { get; set; }
        public Note Note { get; set; }
    }
}
